export const SET_PIZZAS = 'HOME/PIZZAS/SET_PIZZAS'
export const SET_LOADED = 'HOME/PIZZAS/SET_LOADED'

export const SET_SORT_BY = 'HOME/FILTERS/SET_SORT_BY'
export const SET_CATEGORY = 'HOME/FILTERS/SET_CATEGORY'

export const ADD_PIZZA_CART = 'CART/ADD_PIZZA_CART'
